spring:
  application:
    name: clock-in-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/auth/realms/clock-in-realm
      client:
        registration:
          keycloack:
            client-id: clock-in-oauth2-client
            authorization-grant-type: authorization_code
            scope: open_id
        provider:
          keycloack:
            issuer-uri: http://localhost:8181/auth/realms/clock-in-realm
            user-name-attribute: preferred_username
  cloud:
    gateway:
      default-filters:
        - TokenRelay

server:
  port: 9000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

keycloack:
  realm:
    token-url: http://localhost:8181/auth/realms/clock-in-realm/protocol/openid-connect/token

gateway:
  url: http://localhost:9000
