spring:
  application:
    name: clock-in-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URL}
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}}
            authorization-grant-type: authorization_code
            scope: openid, email, profile
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URL}
            user-name-attribute: preferred_username
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - TokenRelay=
        - SaveSession

server:
  port: 9000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

keycloak:
  realm:
    token-url: ${KEYCLOAK_TOKEN_URL}

gateway:
  url: http://localhost:9000
