spring:
  application:
    name: clock-in-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOACK_ISSUER_URL}
      client:
        registration:
          keycloack:
            client-id: ${KEYCLOACK_CLIENT_ID}
            authorization-grant-type: authorization_code
            scope: open_id
        provider:
          keycloack:
            issuer-uri: ${KEYCLOACK_ISSUER_URL}
            user-name-attribute: preferred_username
  cloud:
    gateway:
      default-filters:
        - TokenRelay

server:
  port: 9000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

keycloack:
  realm:
    token-url: ${KEYCLOACK_TOKEN_URL}

gateway:
  url: http://localhost:9000
