version: '3'

services:
  postgres-db:
    container_name: "database_clock-in"
    image: 'bitnami/postgresql'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=development
      - POSTGRES_PASSWORD=development
      - POSTGRES_DB=clock-in-db
  rabbitmq:
    container_name: "rabbitmq_clock-in"
    image: 'rabbitmq:3.13-alpine'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBIT_USER=development
      - RABBIT_PASSWORD=development
  keycloack:
    container_name: "keycloack_clock-in"
    image: "codingpuss/keycloak-silicon:16.1.1"
    restart: always
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_EXTRA_ARGS="-Dkeycloak.profile.feature.upload_scripts=enabled"
    ports:
      - "8181:8080"
    depends_on: [ postgres-db ]