CREATE TABLE IF NOT EXISTS TB_EMPLOYEES (
    EM_ID BIGSERIAL PRIMARY KEY,
    EM_FIRST_NAME VARCHAR(100) NOT NULL,
    EM_LAST_NAME VARCHAR(100),
    EM_EMAIL VARCHAR(200) UNIQUE NOT NULL,
    EM_PASSWORD VARCHAR NOT NULL,
    EM_PROFILE_PICTURE_URL VARCHAR,
    EM_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EM_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TB_PERSONAL_DATAS (
    PD_ID BIGSERIAL PRIMARY KEY,
    PD_PHONE VARCHAR(20),
    PD_STREET VARCHAR(100) NOT NULL,
    PD_ZIPCODE VARCHAR(100) NOT NULL,
    PD_CITY VARCHAR(100) NOT NULL,
    PD_COUNTRY VARCHAR(100) NOT NULL,
    PD_STATE VARCHAR(100) NOT NULL,
    PD_HOUSE_NUMBER VARCHAR(50) NOT NULL,
    PD_COMPLEMENT VARCHAR(200),
    PD_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PD_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PD_EMPLOYEE_ID BIGSERIAL REFERENCES tb_employees(EM_ID) NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_POSITIONS (
       PS_ID BIGSERIAL PRIMARY KEY,
       PS_NAME VARCHAR(50) NOT NULL UNIQUE,
       PS_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
       PS_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

       CONSTRAINT check_position CHECK (PS_NAME in ('HUMAN_RESOURCES', 'EMPLOYEE', 'MANAGER', 'CEO'))
);

CREATE TABLE IF NOT EXISTS TB_SYSTEM_ROLES (
   SR_ID BIGSERIAL PRIMARY KEY,
   SR_ROLE VARCHAR(50) NOT NULL UNIQUE,
   SR_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   SR_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT check_position CHECK (SR_ROLE in ('USER', 'ADMIN'))
);


CREATE TABLE IF NOT EXISTS TB_EMPLOYEE_SYSTEM_ROLES (
       ER_EMPLOYEE_ID BIGSERIAL REFERENCES tb_employees(EM_ID),
       ER_SYSTEM_ROLE_ID BIGSERIAL REFERENCES tb_system_roles(SR_ID),
       ER_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
       ER_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

        CONSTRAINT tb_employe_system_role_pkey PRIMARY KEY (ER_EMPLOYEE_ID, ER_SYSTEM_ROLE_ID)
);

CREATE TABLE IF NOT EXISTS TB_EMPLOYEE_POSITIONS (
    EP_EMPLOYEE_ID BIGSERIAL REFERENCES tb_employees(EM_ID),
    EP_POSITION_ID BIGSERIAL REFERENCES tb_positions(PS_ID),
    EP_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EP_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT tb_employe_position_pkey PRIMARY KEY (EP_EMPLOYEE_ID, EP_POSITION_ID)
);