spring:
  application:
    name: clock-in-employees
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true

server:
  port: 9001
  error:
    include-message: always
    include-stacktrace: never

logging:
  level:
    root: WARN
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR

keycloack:
  server-url: ${KEYCLOACK_SERVER_URL}
  issuer-uri: ${KEYCLOACK_ISSUER_URL}
  realm:
    name: ${KEYCLOACK_REALM}
  client_secret: ${KEYCLOACK_CLIENT_SECRET}
  username_admin: ${KEYCLOACK_USERNAME_ADMIN}
  password_admin: ${KEYCLOACK_PASSWORD_ADMIN}
