spring:
  application:
    name: clock-in-employees
  datasource:
    url: jdbc:postgresql://localhost:5432/clock-in-db
    username: development
    password: development
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true

server:
  port: 9001
  error:
    include-message: always
    include-stacktrace: never

logging:
  level:
    root: WARN
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
