spring:
  application:
    name: clock-in-time-clock
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URL}
  flyway:
    schemas: public2

server:
  port: 9002
  error:
    include-message: always
    include-stacktrace: never

logging:
  level:
    root: WARN
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL}
  issuer-uri: ${KEYCLOAK_ISSUER_URL}
  realm:
    name: ${KEYCLOAK_REALM}
  client_secret: ${KEYCLOAK_CLIENT_SECRET}
  username_admin: ${KEYCLOAK_USERNAME_ADMIN}
  password_admin: ${KEYCLOAK_PASSWORD_ADMIN}



