spring:
  application:
    name: clock-in-time-clock
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        default_schema: public2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URL}
  flyway:
    schemas: public2
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

server:
  port: 9002
  error:
    include-message: always
    include-stacktrace: never

gateway:
  url: http://localhost:9000

logging:
  level:
    root: WARN
    org:
      springframework:
        web: info
      hibernate: ERROR

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL}
  issuer-uri: ${KEYCLOAK_ISSUER_URL}
  realm:
    name: ${KEYCLOAK_REALM}
  client_secret: ${KEYCLOAK_CLIENT_SECRET}
  username_admin: ${KEYCLOAK_USERNAME_ADMIN}
  password_admin: ${KEYCLOAK_PASSWORD_ADMIN}

rabbit:
  queue:
    time-clock: time_clock_queue

